### ISSUE TITLE
The skeleton's skin was rendered incorrectly

### ISSUE THREAD

**Issue by Omgise** [Roadhog360/SimpleSkinBackport#6] opened 2024-09-08 07:51 UTC
![屏幕截图 2024-09-08 153929](https://github.com/user-attachments/assets/ae0140d1-6b2a-43ed-96e2-506a52afc619)
![屏幕截图 2024-09-08 154012](https://github.com/user-attachments/assets/437278d2-f879-4413-86a7-dca09e0c85cf)

**Comment by Roadhog360** [comment] 2024-09-08 08:15
What commit are you currently on?

**Comment by Omgise** [comment] 2024-09-08 08:21
bug submission

**Comment by Omgise** [comment] 2024-09-08 08:22
I found that after removing the SimpleSkinBackport, the skeleton's skin became normal

**Comment by Roadhog360** [comment] 2024-09-08 08:23
> bug submission

That doesn't answer the question. What is the version you are running

**Comment by Omgise** [comment] 2024-09-08 08:25
simpleskinbackport-0d97fd8-master+0d97fd8d97-dirty, sorry for not understanding your meaning earlier, due to the translator's issue

**Comment by Roadhog360** [comment] 2024-09-08 08:32
![2024-09-08_04 29 38](https://github.com/user-attachments/assets/deeeeb05-3948-4c54-843a-c9b383d49338) Can't reproduce the issue; it's probably a mod conflict

**Comment by Omgise** [comment] 2024-09-08 08:42
I will try to find the conflicting mod

**Comment by Roadhog360** [comment] 2024-09-08 08:43
How do zombies, endermen etc look?

**Comment by Omgise** [comment] 2024-09-08 08:45
> How do zombies, endermen etc look?



They look normal, with no rendering errors

**Comment by Omgise** [comment] 2024-09-08 13:22
I found it was back to normal after removing AsieLib (I think it's this mod. I've deleted so many mods I can't remember which one)

**Comment by Roadhog360** [comment] 2024-09-08 21:14
This is a real issue, mod conflicts do need to be resolved.
Something about AsieLib is causing skeletons to be marked as a player.

**Comment by Roadhog360** [comment] 2024-09-08 22:03
![2024-09-08_18 02 48](https://github.com/user-attachments/assets/8e7bb2bf-4ece-496b-8abf-bf6cc57b0e9d)
![2024-09-08_18 03 05](https://github.com/user-attachments/assets/9df4d9bb-9719-4d76-b38a-217225a21283)

After installing AsieLib, I still cannot reproduce the issue. I don't see any code relating to entity rendering in it either.

**Comment by Omgise** [comment] 2024-09-08 22:29
Now I find that backhand is the cause of the problem

**Comment by Omgise** [comment] 2024-09-08 22:32
I used the backhand branch of GTNH:https://github.com/GTNewHorizons/Backhand

**Comment by Roadhog360** [comment] 2024-09-09 00:25
Confirmed with Backhand

**Comment by Roadhog360** [comment] 2024-09-09 00:38
![2024-09-08_20 29 23](https://github.com/user-attachments/assets/a35907a2-bf3d-45a0-805f-63a7f80eb46f)
![2024-09-08_20 29 29](https://github.com/user-attachments/assets/4bab89c2-75a7-4691-bf0c-1b98baff750c)
Happens with zombies too.

**Comment by Roadhog360** [comment] 2024-09-09 09:27
Worked around it but I still think this is a valid issue over on their end; I had to rewrite a significant portion of code to work around it.

**Closed as completed** 2024-09-09 09:27 UTC
